version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow Dependabot to work without a lockfile
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Only update production dependencies defined in pyproject.toml
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "medspacy"
    assignees:
      - "medspacy"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
