language: python
notifications:
  email: false
os:
  - linux
env:
  global:
    - PROJECT_NAME=medspacy_io
    - PYPI_REPO_NAME=medspacy-io
    - PYPI_LOGIN=__token__
    - PY35="cp35-cp35m"
    - PY36="cp36-cp36m"
    - PY37="cp37-cp37m"
    - PY38="cp38-cp38"
    - TRAVIS_PY36=3.6.7
    - TRAVIS_PY37=3.7
    - DEPLOY_TEST=false
    - secure: "kzQuHUMjjGvwL4bFcwywA28ed4wBRi+kx8UtogjffNrYdtuUped0eNRyKXZWl3mPDuqx8DXvkcMF795t2u9UXJtC137P9yX5CoMU14f4Zvv4nZuh082InyKSD036K+0jcKxmJ++sfVEi/X70f2oFW0rAf5rHD2veT4SW5Hxtb9dVaiJVpEXdT1PSXJ5MW2QdNxa/siIuK4uTNBMM0h/hY9i/wydDYgdh0+33cYXB7+X7tEaCIxkM8X1IiUYbzWgkd9StVN7koPxHc0x9c5y0VEd5ESAlHp9wHUr/tHk+OwRQHZXMEsMZrZjbFwNT5vR4vMAKqD5wTr3h4W+dWaihdG/hAU1eeXxh8vyvKwNN6fvE7jehr5z3fbBoGAh/Rhhl4u/kl3+xSqiO1kM2BVqNFcudivhDqkEnOuwfIhaV+bPshmIv61yKeCQiRKJ/JsGCMloBpD7/5pHiwZ0/zCDi6scwzNYVx1P0gvbIzjONXiuImd6zBdPN9/QYa9KErnZIh5tHFRblR0ARH5ws+euogKYw5za6rlyeqK1DWPpQCjTtsElNdtVa/qSG/GSzsfss4CY1a04Qktug+5CkdOKGiiJ2PQsvE9yL01CoayNNgcLZStR/IhLzSG+Li+3Px0ZMey38lK+ZTVJF9ScShfNtf6xBx8VZ2XJgIovCD6BadXw="
    - secure: "GWJ0dFS9amrzso40L+j6Wf5ovhD/l5x9PydgAr/AGOdkVx1/V4X+qpCzrvdal5CYDDBqo+eH5HUbWe7DSDPNlzp+GV3xVA6BL8uC6Eic3RkL/zwuVf1EHKOP6NACAE1i78MiZnPDXTwjLJKh+9XSMsZslWTQ8Bkas+V4XfG044BJb37gZorcFuIPfwNwt4sX1CnY58C0JUXEW3ib0Aa65c2Zs/ZFx2B1hL/AfyLZdkS9YG6bcaFgrJEuVy/6yZfagkFp3NZE4mU8OQHu39Md2UGiUBhw611Ktg4dndvHJDuutPukafh6/6wmK6yV6SnUznLuBGpAqyp7r6e9HrqS/mZRRDS3FRfer8sfh44i9pvznDa/TXLbsdKmq3AuwcVCi1NjDokFgWLmLyDAVdMqQunSFfGGDHMTjuW0Y8t7R28Wbi0zvaGpo15EPnNDDg9jiGseYx5Qq8c66P+qGUCANNocSZkVhEPfNA9l7rSjZh7W39gHz1vf+/xSFnXwlC4/s5aA5Oe6FypZGpbc+Uom8uTKmooK66jOMjn+1RyJkIv/FE/PQjcEFKmIpdr8wx/3XShaSwPfkzysb5G5qVGxmaePhyYA31xfrGxyvIjxWaNmVszK2nuocuO+iS/x+KXL77W9U6npWigcKt1HYjrygT0mdu3oO2h44CVaK24vyR8="


# encrypt PYPI_PWD
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        PLAT=manylinux1_x86_64
    #      drop i686,because SpaCy doesn't support it
    #    - sudo: required
    #      services:
    #        - docker
    #      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #        PRE_CMD=linux32
    #        PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        PLAT=manylinux2010_x86_64

install:
  - /opt/python/${TRAVIS_PY36}/bin/pip install twine
  - /opt/python/${TRAVIS_PY36}/bin/pip install -r dev-requirements.txt
  - docker pull $DOCKER_IMAGE

script:
  - chmod 775 travis/build-wheels.sh
  - docker run --name "aaa36" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY36}"
  - docker run --name "aaa37" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY37}"
  - docker run --name "aaa38" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY38}"

before_deploy: "/opt/python/${TRAVIS_PY36}/bin/python setup.py sdist"

deploy:
  # deploy develop to pypi.org
  - provider: script
    script: echo "deploying..." && ls dist && /opt/python/${TRAVIS_PY36}/bin/python -m twine upload -u ${PYPI_LOGIN} -p ${PYPI_API_TOKEN} --skip-existing dist/*
    skip_cleanup: true
    on:
      tags: true
      condition: "$DEPLOY_TEST == false"

  # deploy develop to test.pypi.org, we want to reuse the customized built from build-wheels, so not using default travis pypi setting.
  - provider: script
    script: echo "deploying..." && ls dist && /opt/python/${TRAVIS_PY36}/bin/python -m twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ -u ${PYPI_LOGIN} -p ${TEST_API_TOKEN} dist/*
    skip_cleanup: true
    on:
      tags: true
      condition: "$DEPLOY_TEST == true"

