language: python
notifications:
  email: false
os:
  - linux
env:
  global:
    - PROJECT_NAME=medspacy_io
    - PYPI_REPO_NAME=medspacy-io
    - PYPI_LOGIN=__token__
    - PY35="cp35-cp35m"
    - PY36="cp36-cp36m"
    - PY37="cp37-cp37m"
    - PY38="cp38-cp38"
    - TRAVIS_PY36=3.6.7
    - TRAVIS_PY37=3.7
    - DEPLOY_TEST=true
    - secure: Jmt9G6ySp+DZAy0mIkYiw5pruDRlUKOM7IALaCjL784cPNpp+9tQade0qoR2F15ZNDzbaAvvRRMI/dD2COiem9jSVN6cQLP+7m3xnx/TS7aGlOASNOqAD9ztbXju3LOfs6QjJJjRVrhzfqKDOF6sNghyX6WErecBy1E53dl91W/RK+BlqmE+751ad47Jh+/8mjK+3nwwdcCYvq+ql8ozrklAmr29Y1ibTsin8B8AQRtaihgmDJlliU989TnH7vWxygE729Bm5VEwY+3GJE0CBsjrQWUiRumBC5liY5tO8v4950pwP8/9cgT8YWBTqGr5Y8L7n772Yss7zt3yBJ9L+9SfWfGcWackZdB1nzUidHt3FkagtJ6ROP5v9yrq8PP4xS8/DPQGKH3EElUMNDCmJ7E1cFx4v73/VdhfExNkhjQnpoLy0jGL4zuEZ0zG3yADRPuMl7l5J+fcfRghP3atDcvD/enmo9kovpu1bAC91MaEHMuKQB3yO/eLtx8sTH2XD9WS9kRN9KdV4b0D6QGbE30JPbwxJspES5fm71HcTz7yD7/WLFSW1pPYJLPoiVpQlsKcZKe2AbnNrLeXBNNOxHR1KQmekowfFu19ylser3B5WDZKNBT5XlrZZg9JzcdMngcuvla0Zjl/youM4+8UUliJQr0K2htUpTI+eXPnv9E=
    - secure: "GWJ0dFS9amrzso40L+j6Wf5ovhD/l5x9PydgAr/AGOdkVx1/V4X+qpCzrvdal5CYDDBqo+eH5HUbWe7DSDPNlzp+GV3xVA6BL8uC6Eic3RkL/zwuVf1EHKOP6NACAE1i78MiZnPDXTwjLJKh+9XSMsZslWTQ8Bkas+V4XfG044BJb37gZorcFuIPfwNwt4sX1CnY58C0JUXEW3ib0Aa65c2Zs/ZFx2B1hL/AfyLZdkS9YG6bcaFgrJEuVy/6yZfagkFp3NZE4mU8OQHu39Md2UGiUBhw611Ktg4dndvHJDuutPukafh6/6wmK6yV6SnUznLuBGpAqyp7r6e9HrqS/mZRRDS3FRfer8sfh44i9pvznDa/TXLbsdKmq3AuwcVCi1NjDokFgWLmLyDAVdMqQunSFfGGDHMTjuW0Y8t7R28Wbi0zvaGpo15EPnNDDg9jiGseYx5Qq8c66P+qGUCANNocSZkVhEPfNA9l7rSjZh7W39gHz1vf+/xSFnXwlC4/s5aA5Oe6FypZGpbc+Uom8uTKmooK66jOMjn+1RyJkIv/FE/PQjcEFKmIpdr8wx/3XShaSwPfkzysb5G5qVGxmaePhyYA31xfrGxyvIjxWaNmVszK2nuocuO+iS/x+KXL77W9U6npWigcKt1HYjrygT0mdu3oO2h44CVaK24vyR8="


# encrypt PYPI_PWD
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        PLAT=manylinux1_x86_64
    #      drop i686,because SpaCy doesn't support it
    #    - sudo: required
    #      services:
    #        - docker
    #      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #        PRE_CMD=linux32
    #        PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        PLAT=manylinux2010_x86_64

install:
  - /opt/python/${TRAVIS_PY36}/bin/pip install twine
  - /opt/python/${TRAVIS_PY36}/bin/pip install -r dev-requirements.txt
  - docker pull $DOCKER_IMAGE

script:
  - chmod 775 travis/build-wheels.sh
  - docker run --name "aaa36" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY36}"
#  - docker run --name "aaa37" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY37}"
#  - docker run --name "aaa38" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY38}"

before_deploy:
  - provider: script
    script: cd io && /opt/python/${TRAVIS_PY36}/bin/python -m setup.py sdist
    on:
      tags: false
      condition: "$DEPLOY_TEST == true"

deploy:
  # deploy develop to pypi.org
  - provider: script
    script: echo "deploying..." && ls dist && /opt/python/${TRAVIS_PY36}/bin/python -m twine upload -u ${PYPI_LOGIN} -p ${TWINE_PASSWORD} --skip-existing wheelhouse/*
    on:
      tags: true
      condition: "$DEPLOY_TEST == false"

  # deploy develop to test.pypi.org, we want to reuse the customized built from build-wheels, so not using default travis pypi setting.
  - provider: script
    script: echo "deploying..." && ls dist && /opt/python/${TRAVIS_PY36}/bin/python -m twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ -u ${PYPI_LOGIN} -p ${TEST_API_TOKEN} dist/*
    skip_cleanup: true
    on:
      tags: false
      condition: "$DEPLOY_TEST == true"

