language: python
notifications:
  email: false
os:
  - linux
env:
  global:
    - PROJECT_NAME=medspacy_io
    - PYPI_REPO_NAME=medspacy-io
    - PYPI_LOGIN=__token__
    - PY35="cp35-cp35m"
    - PY36="cp36-cp36m"
    - PY37="cp37-cp37m"
    - PY38="cp38-cp38"
    - TRAVIS_PY36=3.6.7
    - TRAVIS_PY37=3.7
    - DEPLOY_TEST=true
    - secure: Jmt9G6ySp+DZAy0mIkYiw5pruDRlUKOM7IALaCjL784cPNpp+9tQade0qoR2F15ZNDzbaAvvRRMI/dD2COiem9jSVN6cQLP+7m3xnx/TS7aGlOASNOqAD9ztbXju3LOfs6QjJJjRVrhzfqKDOF6sNghyX6WErecBy1E53dl91W/RK+BlqmE+751ad47Jh+/8mjK+3nwwdcCYvq+ql8ozrklAmr29Y1ibTsin8B8AQRtaihgmDJlliU989TnH7vWxygE729Bm5VEwY+3GJE0CBsjrQWUiRumBC5liY5tO8v4950pwP8/9cgT8YWBTqGr5Y8L7n772Yss7zt3yBJ9L+9SfWfGcWackZdB1nzUidHt3FkagtJ6ROP5v9yrq8PP4xS8/DPQGKH3EElUMNDCmJ7E1cFx4v73/VdhfExNkhjQnpoLy0jGL4zuEZ0zG3yADRPuMl7l5J+fcfRghP3atDcvD/enmo9kovpu1bAC91MaEHMuKQB3yO/eLtx8sTH2XD9WS9kRN9KdV4b0D6QGbE30JPbwxJspES5fm71HcTz7yD7/WLFSW1pPYJLPoiVpQlsKcZKe2AbnNrLeXBNNOxHR1KQmekowfFu19ylser3B5WDZKNBT5XlrZZg9JzcdMngcuvla0Zjl/youM4+8UUliJQr0K2htUpTI+eXPnv9E=


# encrypt PYPI_PWD
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        PLAT=manylinux1_x86_64
#      drop i686,because SpaCy doesn't support it
#    - sudo: required
#      services:
#        - docker
#      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
#        PRE_CMD=linux32
#        PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        PLAT=manylinux2010_x86_64

install:
  - /opt/python/${TRAVIS_PY36}/bin/pip install twine
  - /opt/python/${TRAVIS_PY36}/bin/pip install -r dev-requirements.txt
  - docker pull $DOCKER_IMAGE

script:
  - chmod 775 travis/build-wheels.sh
  - docker run --name "aaa36" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY36}"
#  - docker run --name "aaa37" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY37}"
#  - docker run --name "aaa38" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/sh -c "/io/travis/build-wheels.sh ${PLAT} ${PROJECT_NAME} ${PY38}"



deploy:
  # deploy develop to pypi.org
  - provider: script
    script: echo "deploying..." && ls wheelhouse && /opt/python/${TRAVIS_PY36}/bin/python -m twine upload -u ${PYPI_LOGIN} -p ${TWINE_PASSWORD} --skip-existing wheelhouse/*
    on:
      tags: true
      condition: "$DEPLOY_TEST == false"

  - provider: pypi
    user: "__token__"
    server: https://test.pypi.org/legacy/
    password:
      secure: "sZJ8xVU05gOSPuyK4foClIt9xHAaUmpqqCyZGIkgkL4/aNxULet1/1PQc26coka4YCgLCPdZzSD2io6inhkD0NAR33RlmYjwABZdWYMRFG9z+8f9nmB+5zCtQ063J7CiaworcqFtWkkMa8x0Kpqw77H/1MLZEI0B0sTl5dwdvD5GXVIB2D2jwm9mXPxHJ43HclTcOHOmHLROBDGanUc595jcurIDEg1uxY6+BDQ4ziRk8VMRUBGRACe6tCehxzIsb3wgRNuovXfXwaQqc7LlrK/XMg/MTx1itAT5pDU1JftnobxQ8ASCg41U5n80QC4g6BbjbUxKnEQVRkll/UN5QRq9YlQLFGN+ArFjFVXxo7+QwDHvviO3cZv/D6Yd7d1IPnd20AuWQGpkIljQuuPKTFdHzHru7p1dn8BpapfRQZq8yQJZf42WYqCkEyciCcqIIyni8Qa6XVGwWy879YodHySkWeaSICUhT8XpjPyf4EjG2xIbXgEapGRVuzcvx6DDbgr+jotYodlDD8IyPkf3m3wjfvkDDeaQUYOy+aDqKCNx0n+jCXUreXaZ9XK82Y2xaVYgT9SI5QOxt3P1mZTcyWK5Md1br1XK9zxRZp2gkv/LkNekYo0PBvW19xpqOLA6HA4z7notMRF/57vEJTWn3sWBkptvt8+er9q3/A6KfWo="
    skip_cleanup: true
    skip_existing: true
    verbose: true
    on:
      tags: false
      condition: "$DEPLOY_TEST == true"

#  # deploy develop to test.pypi.org
#  - provider: script
#    script: echo "deploying..." && ls wheelhouse && /opt/python/${TRAVIS_PY36}/bin/python -m twine upload -u ${PYPI_LOGIN} --repository-url https://test.pypi.org/legacy/ -p ${TWINE_PASSWORD} --skip-existing wheelhouse/*
#    on:
#      tags: false
#      condition: "$DEPLOY_TEST == true"

